ALTER TABLE `directory_groups` ADD `session_types` text DEFAULT '' NOT NULL;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Jaguar', name = 'La Fe Que Obra', city = 'Mérida, Yucatán', leader_name = 'Verónica Montero Herrera', whatsapp = '9995694800', email = 'veronicamontero44@gmail.com', facebook = '', address = '53a 346 x 20 y 22 juan Pablo ll', maps_url = '', schedules = 'Lunes a sábado de 8 a 10', session_types = '', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 21;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Jaguar', name = 'Un Nuevo Despertar', city = 'Mérida, Yucatán', leader_name = 'Daniel Octavio López González', whatsapp = '9992440631', email = 'danieloctaviolopezgonzalez429@gmail.com', facebook = '', address = 'Col. Nueva Chichén, calle 25 entre 20 y 22a #547', maps_url = '', schedules = 'Lunes a sábado de 8 a 10 y domingos de 7 a 9', session_types = '', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 37;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Jaguar', name = 'Ángeles de un Ala', city = 'Yucatán', leader_name = 'Angel Xooc', whatsapp = '9993574304', email = 'jokerxooc39@gmail.com', facebook = 'https://www.facebook.com/share/1DYx69Jrv5/', address = 'Cerrito mulchechen calle 70 x 75 kanasin s/n', maps_url = '', schedules = 'Lunes a viernes de 8 30 a 10 30', session_types = '', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 14;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Jaguar', name = 'Creo en Ti', city = 'Mérida, Yucatán', leader_name = 'Patricia Briceño Gamboa', whatsapp = '9993277221', email = 'bric.patrici@gmail.com', facebook = '', address = 'C. 46 B # 595 x 103 y 103 A Col. Santa Rosa C. P. 97279 Mérida Yucatán', maps_url = '', schedules = 'De lunes a sábado de 8 a 10 p. m.', session_types = '', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 6;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Jaguar', name = 'Alas de Libertad', city = 'Tixkokob, Yucatán', leader_name = 'Martin Ulices Madera Fernández', whatsapp = '9911106068', email = 'martinmaderafernandez@gmail.com', facebook = '', address = 'Calle 26 x 17 y 19', maps_url = '', schedules = '6 dias de sesión y de 8:00 a 10:00pm', session_types = '', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 1;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Jaguar', name = 'Renacer Sotuta', city = 'Sotuta, Yucatán', leader_name = 'José Eduardo Pérez Góngora', whatsapp = '9994168626', email = 'eduperluz@gmail.com', facebook = '', address = 'Calle 19 x 20 y 22 S/N. Col. Centro. Sotuta, Yucatán. CP 97690', maps_url = '', schedules = 'De lunes a sábado. De 8:30 a 10:30 p. m.', session_types = '', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 32;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Jaguar', name = 'Umán', city = 'Umán, Yucatán', leader_name = 'Luis Alfonso Mex Martínez', whatsapp = '9993554171', email = 'luismexm@gmail.com', facebook = '', address = 'Calle 13 no 89 por 16 col la mejorada UMÁN', maps_url = '', schedules = 'La mes a viernes de 8 a 10 p. m.', session_types = '', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 35;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Jaguar', name = 'Itzincab', city = 'Umán, Yucatán', leader_name = 'Landy Esther Valdez Céh', whatsapp = '9999082571', email = 'landyvaldes2@gmail.com', facebook = '', address = 'Calle 42 x 29', maps_url = '', schedules = 'De lunes a sábado de 8 a 10 p. m..', session_types = '', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 18;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Jaguar', name = 'Fuerza y Libertad', city = 'Mérida, Yucatán', leader_name = 'Joel Mena', whatsapp = '9618013021', email = 'mcojoel19@gmail.com', facebook = 'https://www.facebook.com/share/1DPCja93Tb/', address = 'Calle 18A #40 x 75, Morelos Oriente, 97174, Mérida, Yuc.', maps_url = '', schedules = 'L-S 8.30 a 10.30pm', session_types = '', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 12;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Jaguar', name = 'Francisco de Montejo', city = 'Mérida, Yucatán', leader_name = 'Carlos Eduardo González Rodríguez', whatsapp = '9843146184', email = 'talipollo69@gmail.com', facebook = '', address = 'Calle 57a #371 x 57 y 58 Francisco de Montejo CP 97203 Mérida Yucatán', maps_url = '', schedules = 'Lunes a viernes 8 a 10', session_types = '', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 11;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Jaguar', name = 'Homún', city = 'Yucatán', leader_name = 'José Edilberto Pool Euan', whatsapp = '9991999883', email = 'pooleuanjoseedilberto12@gmail.com', facebook = '', address = 'Calle 18 x 11 y 13 homun Yucatán', maps_url = '', schedules = 'Lunes, miércoles, viernes, sábado de 8:30 pma 10:30 p. m.', session_types = '', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 17;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Jaguar', name = 'Fe, Esperanza y Fortaleza', city = 'Yucatán', leader_name = 'Lidia María Ceballos Santiago', whatsapp = '9991488540', email = 'ceballossantiagolidia@gmail.com', facebook = '', address = 'Calle 55 sin número x 2 y4, Francisco villa, 97370', maps_url = '', schedules = 'Lunes a sábado, d 8:30 a 10:30', session_types = '', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 9;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Jaguar', name = 'Tercera Promesa', city = 'Mérida, Yucatán', leader_name = 'Yajaira Pacheco', whatsapp = '9995082600', email = 'yajapacheco84@gmail.com', facebook = '', address = 'C157c #108 /19 30y32 villa bonita', maps_url = '', schedules = 'De lunes a sabado sesión general Martes y jueves sesión de diversidad', session_types = 'Sesión Principal (dos Horas por la Noche), Diversidad Con Dignidad (lgbttiq+)', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 34;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Jaguar', name = 'Atenea Altabrisa', city = 'Yucatán', leader_name = 'Areleyna Guadalupe González Albornoz', whatsapp = '9992342628', email = 'arelupita22@gmail.com', facebook = '', address = 'C.7a # 365 x 2A col. Díaz Ordaz', maps_url = '', schedules = '8 p. m. a 10 p. m.', session_types = '', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 2;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Jaguar', name = 'Templarios', city = 'Yucatán', leader_name = 'Rolando Guillermo Cortazar Segovia', whatsapp = '9991000389', email = 'clientemacro2223@gmail.com', facebook = 'https://www.facebook.com/share/1D9jS4MZCe/', address = 'Calle 71 #790 x 100 y 102 almendros 3, ciudad Caucel Cp. 97314', maps_url = '', schedules = 'Lunes a domingo 8:00pm a 10:00pm', session_types = '', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 33;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Jaguar', name = 'El Lenguaje del Corazón', city = 'Yucatán', leader_name = 'Marisol Valdez Solorzano', whatsapp = '9994163820', email = 'marisolvaldez354@gmail.com', facebook = '', address = 'Calle 71A 86y88#683 almendros 2 CD caucel código postal 97314', maps_url = '', schedules = 'Lunes a sábado 8:00pm a 10 :00calle 71pm', session_types = '', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 31;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Jaguar', name = 'Ixil', city = 'Yucatán', leader_name = 'Jesús Bernabé Tun Coba', whatsapp = '9999912295', email = 'bernabetuncoba@gmail.com', facebook = 'https://www.facebook.com/share/p/18fHXyeoui/', address = 'C. 17 No. 81 C x 14 Ixil Yucatan', maps_url = '', schedules = 'De lunes a viernes de 8:30pm a 10:30pm, sábado sesión de media noche de 11:00pm a 1:00am y domingo sesión de jóvenes de 6:30pm a 8:30pm', session_types = '', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 19;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Jaguar', name = 'Forjando Un Camino', city = 'Yucatán', leader_name = 'Gilberto Domínguez', whatsapp = '9991367790', email = 'tazito17.gd@gmail.com', facebook = '', address = 'Carretera nolo yaxkukul rancho la concepción', maps_url = '', schedules = 'Lunes a viernes de 8:00 p. m. a 10:00 p. m.', session_types = '', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 10;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Jaguar', name = 'Un Corazón Agradecido', city = 'Yucatán', leader_name = 'Nelsi María Morales Bacab', whatsapp = '9992709913', email = 'nelsif23@gmail.com', facebook = '', address = 'C.25x14y16S/N Colonia comisaria san José Tzal Ciudad. Mérida Yucatán 97315', maps_url = '', schedules = 'De lunes a viernes de 8:30 a 10:30', session_types = '', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 36;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Jaguar', name = 'Familia Fénix', city = 'Yucatán', leader_name = 'María Elizabeth Góngora Cervantes', whatsapp = '9971241864', email = 'tunyjesus@hotmail.com', facebook = '', address = 'Calle 58 num 193 x 47 y 49 col San Francisco Tekax Yucatán. Codigo postal 97970', maps_url = '', schedules = 'De lunes a sábado de 7 a 9 p. m.', session_types = '', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 13;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Jaguar', name = 'La Cuna', city = 'Yucatán', leader_name = 'José Alfonso Cortázar Segovia', whatsapp = '9992004361', email = '', facebook = 'https://www.facebook.com/lacunagdll', address = 'Calle 60 #729 por 91 y 93 centro.', maps_url = '', schedules = 'De lunes a domingo', session_types = '', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 20;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Tiburón', name = 'Esencia del Alma', city = 'Valladolid', leader_name = 'Pamela Beatriz Mendoza Vivas', whatsapp = '9851004750', email = 'betty7813@hotmai.com', facebook = '', address = 'Calle 31 núm 196D por 36 y 38 Santa Lucía Cp. 97780 Valladolid Yucatán', maps_url = '', schedules = 'Lunes a sábado de 8:00 a 10:00 p. m.', session_types = '', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 45;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Tiburón', name = 'El Faro', city = 'Tulum', leader_name = 'Adrián Irineo', whatsapp = '9983216038', email = 'hirineo16@hotmail.com', facebook = '', address = 'Calle Cecilio Chi, Col. Triunfadores, Tulum Q. Roo', maps_url = '', schedules = 'Lunes a Sábado 8:30 p. m. a 10:30 p. m.', session_types = '', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 44;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Tiburón', name = 'Fuente de Vida', city = 'Valladolid', leader_name = 'Pedro Cocom Cotik', whatsapp = '9851156393', email = 'cocom777@gmail.com', facebook = '', address = 'Calle 14 / 38 y 39 col militar, Valladolid Yuc 97780', maps_url = '', schedules = 'Lunes a sábado de 8:00 a 10:00 p. m.', session_types = '', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 48;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Tiburón', name = 'Ángeles', city = 'Cozumel', leader_name = 'Guadalupe de Jesús Garma Fernández', whatsapp = '9871128263', email = 'nenita_soid@hotmail.com', facebook = '', address = '40 avenida entre 5 e hidalgo', maps_url = '', schedules = 'Lunes a sábado 8:00 p. m. a 10:00 p. m.', session_types = '', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 66;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Tiburón', name = 'Cancún', city = 'Cancún Q Roo', leader_name = 'Armando Roberto Juan Carlos Rojas Morales', whatsapp = '9987760123', email = 'guerreroscancunqroo@gmail.com', facebook = '', address = 'Region 92 sobre ruta 4 y av kabah', maps_url = '', schedules = 'De lunes a sábados de 7:00 a 9:00', session_types = '', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 40;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Tiburón', name = 'Cozumel', city = 'Cozumel', leader_name = 'Tony Maldonado', whatsapp = '9875646516', email = 'toni.chable.chable@gmail.com', facebook = 'https://www.facebook.com/share/1LRMwHffqq/', address = '90 AV BIS ESQUINA CON MORELOS, COLONIA REPOBLADORES', maps_url = '', schedules = 'Lunes a Sábado de 08.00 p.m. a 10.00 p.m.', session_types = '', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 43;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Tiburón', name = '70 Veces 7', city = 'Valladolid', leader_name = 'Ivan Tejero', whatsapp = '9851098695', email = 'ivantejerovaldez24@gmail.com', facebook = '', address = 'Calle 56 por 41 y 43 col. Bacalar', maps_url = '', schedules = 'De lunes a sábado', session_types = '', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 38;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Tiburón', name = 'Tulum', city = 'Tulum', leader_name = 'Kevin May', whatsapp = '9841676098', email = 'maynohkevin@gmail.com', facebook = 'https://www.facebook.com/share/1D1SvAPihd/', address = 'C. Faisan, entre C. 12 y 2D, Col. Tumben kah, Tulum, Quintana Roo, Cp. 77760', maps_url = '', schedules = 'Lunes a sábado de 8:30 a 10:30', session_types = '', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 63;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Tiburón', name = 'Valladolid', city = 'Valladolid', leader_name = 'Roger Oswaldo Casanova Uc', whatsapp = '9858580500', email = 'roch0521@gmail.com', facebook = '', address = 'Calle 44 No. 157 A x 27 A y 29 Colonia Santa Lucía', maps_url = '', schedules = 'De lunes a sábado de 8 a 10 p. m.', session_types = '', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 64;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Tiburón', name = 'Transformación', city = 'Cancun Quintana Roo', leader_name = 'Luis Gerardo Ramos Diaz', whatsapp = '9992386290', email = 'luis.ramos2967@gmail.com', facebook = '', address = 'Sm 73 manzana 2 lote 3 calle 36', maps_url = '', schedules = '6 lunes a sábado de 8 a 10 p. m.', session_types = '', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 62;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Tiburón', name = 'La Buena Voluntad', city = 'Quintanas roo', leader_name = 'Jose David Alvarez Flores', whatsapp = '9871055246', email = 'davidflores98066@gmail.com', facebook = '', address = 'Calle camarón col. 55 aun costado del templo azul código postal 77976', maps_url = '', schedules = 'Lunes a viernes 8:30 a 10:30 p. m.', session_types = '', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 51;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Tiburón', name = 'Concédeme la Serenidad', city = 'Felipe Carrillo Puerto Quintana Roo', leader_name = 'Martha Eugenia Martinez Balam', whatsapp = '9831065106', email = 'mareu84@hotmail.com', facebook = 'https://www.facebook.com/share/1DZFaqjaN1/', address = 'Calle 51 x 50A Col. Javier Rojo Gómez en Felipe Carrillo Puerto Quintana Roo', maps_url = '', schedules = 'Lunes a viernes de 8 a 10 y domingos de 12 a 2 p. m. sesión de jóvenes', session_types = '', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 42;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Tiburón', name = 'Nueva Vida', city = 'Canacun', leader_name = 'Fatima del Socorro Canto Villanueva', whatsapp = '9982410833', email = 'fatimavillanueva0833@gmail.com', facebook = '', address = 'region 99 mza 27 lote 1 x a.v135 y calle 8', maps_url = '', schedules = 'de lunes a sabado de 8:00 a 10 :00 p.m', session_types = '', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 53;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Tiburón', name = 'Chetumal', city = 'Chetumal, Qroo', leader_name = 'Fabián Manuel Kuc Peña', whatsapp = '9831716821', email = 'fabiankuc849@gmail.com', facebook = '', address = 'Av. Heroes 293 entre camelias y justo sierra. Cp. 77000. O.P.Blanco', maps_url = '', schedules = 'De lunes a sábado de 8 p. m. a 10 p. m.', session_types = 'Sesión Principal (dos Horas por la Noche)', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 41;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Tiburón', name = 'Vuelo de Libertad', city = 'Valladolid, Yucatán', leader_name = 'Isabel Cervera Sosa', whatsapp = '9851118097', email = 'isabel.cervera.sosa@gmail.com', facebook = '', address = 'C 41 num 309 entre 66 y 68', maps_url = '', schedules = 'Lunes a viernes de 8 a 10 p. m.', session_types = 'Sesión Principal (dos Horas por la Noche)', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 65;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Tiburón', name = 'Refugio del Alma Piste', city = 'Pisté de Chichén, Yucatán', leader_name = 'Jose Luis Flores Jimenez', whatsapp = '9858527226', email = 'joseluisfloresjimenez519@gmail.com', facebook = '', address = 'Calle 11 # 22 SN piste 57757', maps_url = '', schedules = 'Lunes a viernes de 8 30 a 10 30', session_types = 'Sesión Principal (dos Horas por la Noche)', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 58;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Tiburón', name = 'Paso Doce', city = 'Valladolid, Yucatán', leader_name = 'Alejandro Rodríguez', whatsapp = '9851095789', email = 'tokadiskoz@gmail.com', facebook = 'https://www.facebook.com/share/1Dz9kektTN/', address = 'Calle 51 x 50 y 52 barrio de sisal Esquina 97780', maps_url = 'https://maps.app.goo.gl/nrvHcKXsHB5utxrr8', schedules = 'Lunes a Viernes de 8:00 a 10:00', session_types = 'Sesión Principal (dos Horas por la Noche)', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 54;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Tiburón', name = 'Hunab Kú', city = 'Playa del Carmen, Quintana Roo', leader_name = 'Vicente Vallin', whatsapp = '9841182129', email = 'vicentevallin@hotmail.com', facebook = 'https://www.facebook.com/hunab.ku.guerreros.luz', address = 'Calle 17 sur entre diagonal 85 y 90 avenida colonia Forjadores', maps_url = 'https://share.google/DAmwuOD9pilcs7mZl', schedules = 'de Lunes a Sábado de 8:00 p. m. a 10:00 p. m.', session_types = 'Sesión Principal (dos Horas por la Noche), Jóvenes (15 - 25 Años Aprox)', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 50;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Tiburón', name = 'Adn Playa del Carmen', city = 'Playa del Carmen, Quintana Roo', leader_name = 'Roman Alexis Marin Diaz', whatsapp = '9842076328', email = 'romandiaz1350@gmail.com', facebook = 'https://www.facebook.com/share/1EU72uJLaH/', address = 'Playa del carmen quintana roo colonia colocio AV.COLOCIO CON 25 Y 30 CODIGO POSTAL 77710', maps_url = '', schedules = 'De lunes a sabado de 8:30 a 10:30 p. m.', session_types = 'Sesión Principal (dos Horas por la Noche)', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 39;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Tiburón', name = 'Renacer Quintana Roo', city = 'Benito Juarez,cancún, Quintana Roo', leader_name = 'Hector Dzul Pech', whatsapp = '9983036062', email = 'hectordzul96@gmail.com', facebook = 'https://www.facebook.com/', address = 'AV, TORCASITA ENTREA RUTA 5 Y TALLERES', maps_url = 'https://www.google.com/maps/place/Guerreros+de+la+luz+Renacer+Q.Roo/@21.1785738,-86.8349354,17z/data=!3m1!4b1!4m6!3m5!1s0x8f4c2d007602b08d:0x7a380a361be22b03!8m2!3d21.1785738!4d-86.8349354!16s%2Fg%2F11zk1mys0y?entry=ttu&g_ep=EgoyMDI2MDgxNy4wIKXMDSoASAFQAw%3D%3D', schedules = 'LUNES A SABADO DE 8 p. m. A 10 p. m.', session_types = 'Sesión Principal (dos Horas por la Noche), Jóvenes (15 - 25 Años Aprox)', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 59;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Tiburón', name = 'Polaris', city = 'Cancún, Quintana Roo', leader_name = 'Fernando Jiménez', whatsapp = '9841835327', email = 'ferchoji99@gmail.com', facebook = '', address = 'Av 103 norte y calle 78 Sm 221', maps_url = 'https://maps.app.goo.gl/kLeRUeR7kBWKzX778?g_st=ic', schedules = 'Lunes a sábado de 8 a 10 p. m.', session_types = 'Sesión Principal (dos Horas por la Noche)', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 57;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Tiburón', name = 'Pegaso', city = 'Playa del Carmen, Quintana Roo', leader_name = 'Miguel Angel Hernandez Perez', whatsapp = '9842563311', email = 'mhernandezpe@xcaret.com', facebook = '', address = 'SM1 MZ12 LT4 C PLAYERITOS #32, PCN FRACC PESCADORES FC. P.77710 SOLIDARIDAD QR.', maps_url = '', schedules = 'lunes a viernes de 8:30 a 10:30 p. m.', session_types = 'Sesión Principal (dos Horas por la Noche)', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 55;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Tiburón', name = 'Espita', city = 'Espita, Yucatán', leader_name = 'Isabel Yam Dzul', whatsapp = '9868610427', email = 'yamdzulmariaisabel@gmail.com', facebook = '', address = 'Calle 22 entre 15 y 17 Espita Yucatan', maps_url = '', schedules = 'Lunes a sábado de 8 a 10 p. m.', session_types = 'Sesión Principal (dos Horas por la Noche)', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 46;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Tiburón', name = 'Felipe carrillo puerto', city = 'Felipe Carrillo Puerto, Quintanaroo', leader_name = 'Gabriel Jesus Canul Manzanero', whatsapp = '9838092970', email = 'gabriel120580@gmail.com', facebook = '', address = 'Calle 66 x 73 y avenida lázaro cardenas', maps_url = '', schedules = 'Lunes a sábado 8:30 p. m.', session_types = 'Sesión Principal (dos Horas por la Noche)', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 47;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Tiburón', name = 'Metamorfosis', city = 'Tulum, Quinta Roo', leader_name = 'Diana Hernández', whatsapp = '9841780747', email = 'dianahernandez.raisegroup@gmail.com', facebook = '', address = '77760', maps_url = '', schedules = '8:30 10:30 lunes a sábado', session_types = 'Sesión Principal (dos Horas por la Noche)', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 52;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Delfín', name = 'Champotón', city = 'Champotón, Campeche', leader_name = 'Roberto Contreras Castillo', whatsapp = '9844313664', email = 'coro55429@gmail.com', facebook = '', address = 'Calle 15b entre 16 y 18 col. Manguitos CP 24400 Champoton a media cuadra antes de', maps_url = '', schedules = 'lunes a Sábado de 8 a 10 p. m., Domingo 6 a 8 p. m.', session_types = 'Sesión Principal (dos Horas por la Noche)', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 73;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Delfín', name = 'Teocalli', city = 'Ciudad del Carmen, Campeche', leader_name = 'Víctor Manuel Naal Salvador', whatsapp = '9384055697', email = 'victor@gmail.com', facebook = 'https://www.facebook.com/share/1HbAAtZeUV/?mibextid=wwXIfr', address = 'Calle 45 entre 36 y 38 colonia tecolutla', maps_url = '', schedules = 'Lunes-viernes 8a10pm Sábado 6 a 8pm Domingo unidad', session_types = 'Sesión Principal (dos Horas por la Noche), Jóvenes (15 - 25 Años Aprox), Diversidad Con Dignidad (lgbttiq+)', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 77;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Tiburón', name = 'Playa del Carmen', city = 'Playa del Carmen, Quintana Roo', leader_name = 'Marisol Arana Cruz', whatsapp = '9842149974', email = 'aranamarisol157@gmail.com', facebook = 'https://www.facebook.com/share/1H5BC5kqFe/', address = 'Calle 120 entre 12 y 14, colonia Ejido, 77720, Solidaridad', maps_url = '', schedules = 'Lunes a sábado de 8:30pm a 10:30pm', session_types = 'Sesión Principal (dos Horas por la Noche)', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 56;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Tiburón', name = 'Sembrando Amor', city = 'Chetumal, Othón P. Blanco, Quintana Roo', leader_name = 'Luis Ariel', whatsapp = '9831399822', email = 'luiscaamal@hotmail.com', facebook = '', address = 'Naranjal 278 entre pascual coral y Thomas aznar colonia nueva Esperanza C. P 77086 othon p. Blanco', maps_url = '', schedules = 'Lunes a sábado de 8 a 10pm', session_types = 'Sesión Principal (dos Horas por la Noche)', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 60;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Delfín', name = 'Camino a la Felicidad', city = 'Ciudad del Carmen, Campeche', leader_name = 'Karina Colli', whatsapp = '9381577605', email = 'chivito2217@gmail.com', facebook = '', address = 'C Guadalupe Victoria #65, entre Miguel Hidalgo y costilla y periférica norte Cp 24197, ciudad del Carmen', maps_url = 'https://maps.app.goo.gl/ZLPsGFcXDmKvetP47?g_st=ac', schedules = 'De lunes a Domingo de 20:00 a 22:00', session_types = 'Sesión Principal (dos Horas por la Noche), Jóvenes (15 - 25 Años Aprox)', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 68;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Delfín', name = 'Renacimiento', city = 'Ciudad del Carmen, Campeche', leader_name = 'Carlos Sánchez Velasco', whatsapp = '9381711161', email = 'carlitossannz3@gmail.com', facebook = 'https://www.facebook.com/share/1BYiucNkn1/?mibextid=wwXIfr', address = 'CP 24155', maps_url = '', schedules = 'Lunes a viernes de 10:00 p. m. Sábados de 6:00 p. m. a 8:00 p. m. Y domingos unidades de 8:00 p. m. a 10:00 p. m.', session_types = 'Sesión Principal (dos Horas por la Noche)', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 76;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Delfín', name = 'Cd del carmen', city = 'Carmen, Campeche', leader_name = 'Verónica López', whatsapp = '9381284306', email = 'laureano151604@gmail.com', facebook = '', address = 'Avenida camarón sin número esquina con 70 cod postal 24114 col. Justo Cierra munición Carmen', maps_url = '', schedules = 'De lunes a domingo de 8 a10', session_types = 'Sesión Principal (dos Horas por la Noche)', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 71;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Tiburón', name = 'Génesis', city = 'Playa del Carmen, Quintana Roo', leader_name = 'Belisario Moreno', whatsapp = '9841794272', email = 'belisario_p12@hotmail.comb', facebook = 'https://www.facebook.com/share/1A3E3AkmZJ/', address = 'Villamar 2 av azores casa nunero 10', maps_url = '', schedules = 'Lunes a sábado 8:30a 10:30', session_types = 'Sesión Principal (dos Horas por la Noche)', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 49;
--> statement-breakpoint
UPDATE directory_groups SET zone = 'Delfín', name = 'Campeche', city = 'San Francisco de Campeche', leader_name = 'Ariel', whatsapp = '9911328057', email = 'arielcornecfe@gmail.com', facebook = 'https://www.facebook.com/share/1EDuBk4WNW/', address = 'Calle Queretaro, número 13, colonia. Santa ana, entre Perú y Paraguay', maps_url = 'https://maps.app.goo.gl/vXxe2hKrcasz7p7H7', schedules = 'Lunes a viernes de 8 a 10pm y sábados de 6 a 8 p. m.', session_types = 'Sesión Principal (dos Horas por la Noche)', version = version + 1, verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, updated_by = 'formulario-homologado-2026' WHERE id = 70;
--> statement-breakpoint
INSERT OR IGNORE INTO directory_groups (zone, name, city, leader_name, whatsapp, email, facebook, address, maps_url, schedules, session_types, status, verified_at, updated_by) VALUES ('Jaguar', 'Resiliencia', 'Mérida, Yucatán', 'Marco Antonio Carrillo Solis', '9992306169', 'flyncarr@gmail.com', '', 'Calle 8 #356 x 45 y 47 Col. Melchor Ocampo 2', '', 'Lunes a Viernes de 8:30 a 10:30 p. m.', '', 'active', CURRENT_TIMESTAMP, 'formulario-homologado-2026');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_groups (zone, name, city, leader_name, whatsapp, email, facebook, address, maps_url, schedules, session_types, status, verified_at, updated_by) VALUES ('Jaguar', 'El Mundo de los Iguales', 'Mérida, Yucatán', 'Mariana Heredia', '9601451683', 'marianamishellherediaflores@gmail.com', '', 'C.46#400 col.pacabtun', '', 'Lunes a viernes 8:00 p. m. a 10:00 p. m.', '', 'active', CURRENT_TIMESTAMP, 'formulario-homologado-2026');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_groups (zone, name, city, leader_name, whatsapp, email, facebook, address, maps_url, schedules, session_types, status, verified_at, updated_by) VALUES ('Jaguar', 'Kanasín', 'Kanasín, Yucatán', 'José Luis Millan', '9991897385', 'jlmillancervera@gmail.com', '', 'CALLE 69 POR 12 Y 14 XELPAC KANASIN', '', 'De lunes a domingo de 8:30 a 10:30', '', 'active', CURRENT_TIMESTAMP, 'formulario-homologado-2026');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_groups (zone, name, city, leader_name, whatsapp, email, facebook, address, maps_url, schedules, session_types, status, verified_at, updated_by) VALUES ('Jaguar', 'Ticul', 'Ticul, Yucatán', 'Saúl de Jesús Cetz Gutiérrez', '9971977601', 'saulcetz@gmail.com', '', 'C. 25 x 22 y 24 No. 191K centro de Ticul', '', 'Lunes a Sábado de 8 a 10 p. m.', '', 'active', CURRENT_TIMESTAMP, 'formulario-homologado-2026');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_groups (zone, name, city, leader_name, whatsapp, email, facebook, address, maps_url, schedules, session_types, status, verified_at, updated_by) VALUES ('Jaguar', 'Emiliano Zapata Sur', 'Mérida, Yucatán', 'Ariana Reyes García', '9993690350', 'aris2407@hotmail.com', '', 'C 90 n 339 x 157 y 159 Emiliano zapata, Yucatán', '', 'Lunes a viernes de 8:30 a 10:30 p. m. sabado y domingo de 8 a 10 p. m.', '', 'active', CURRENT_TIMESTAMP, 'formulario-homologado-2026');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_groups (zone, name, city, leader_name, whatsapp, email, facebook, address, maps_url, schedules, session_types, status, verified_at, updated_by) VALUES ('Jaguar', 'Perla Negra', 'Mérida, Yucatán', 'Luis Enrique Domínguez Carrillo', '9901231084', 'jujohersamaster@hotmail.com', '', 'C16 x c. Colonias y 25 colonia María Luisa', '', 'De lunes a domingo de 8:30 a 10:30', '', 'active', CURRENT_TIMESTAMP, 'formulario-homologado-2026');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_groups (zone, name, city, leader_name, whatsapp, email, facebook, address, maps_url, schedules, session_types, status, verified_at, updated_by) VALUES ('Jaguar', 'El Alfarero', 'Cholul, Yucatán', 'Griselda Ayil Poot', '9994566764', 'ayilgriselda@gmail.com', '', 'Calle 21X22 y 24 Cholul centro', '', 'Lunes a viernes de 8:30 a 10:30', '', 'active', CURRENT_TIMESTAMP, 'formulario-homologado-2026');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_groups (zone, name, city, leader_name, whatsapp, email, facebook, address, maps_url, schedules, session_types, status, verified_at, updated_by) VALUES ('Jaguar', 'Renacer — la Fuerza de la Esperanza', 'Yucatán', 'Gabriela Beatriz Blanco Koyoc', '9991056819', 'gblanco1887@gmail.com', '', 'C41 #423 x 52 y 54 Mulchechen II Kanasín', '', 'Lunes a Viernes 8:30pm a 10:30pm', '', 'active', CURRENT_TIMESTAMP, 'formulario-homologado-2026');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_groups (zone, name, city, leader_name, whatsapp, email, facebook, address, maps_url, schedules, session_types, status, verified_at, updated_by) VALUES ('Jaguar', 'Huhí', 'Huhí, Yucatán', 'Jesús Gerardo Dzul', '9992153645', 'dzul3830@gmail.com', '', 'Calle 30x21huhi yucatan 97590', '', 'Lunes ,miércoles,viernes, sábado 8:00pm', '', 'active', CURRENT_TIMESTAMP, 'formulario-homologado-2026');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_groups (zone, name, city, leader_name, whatsapp, email, facebook, address, maps_url, schedules, session_types, status, verified_at, updated_by) VALUES ('Jaguar', 'Déjame Ayudarte', 'Cd. Caucel, Mid, Yucatán', 'María Guadalupe Maldonado Pech', '9991198616', 'conferenciaslupita@gmail.com', '', 'Calle 47 entre 90 y 92 frac arboledas num 696 ciudad caucel', '', 'De lunes a sábado de 8pm a 10pm.', '', 'active', CURRENT_TIMESTAMP, 'formulario-homologado-2026');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_groups (zone, name, city, leader_name, whatsapp, email, facebook, address, maps_url, schedules, session_types, status, verified_at, updated_by) VALUES ('Jaguar', 'Acanceh', 'Acanceh, Yucatán', 'Jorge Armando Xooc Ku', '9993727699', 'armandoxooc1@gmail.com', '', 'Calle 34 sn x 21 y 19 acanceh, código postal 97380, acanceh yucatan', '', 'Lunes a viernes de 8:30 a 10:30', '', 'active', CURRENT_TIMESTAMP, 'formulario-homologado-2026');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_groups (zone, name, city, leader_name, whatsapp, email, facebook, address, maps_url, schedules, session_types, status, verified_at, updated_by) VALUES ('Jaguar', 'El Valor de Seguir', 'Yucatán', 'Elicarmen Aguilar Aldaz', '9997384839', 'elizabeth268910@gmail.com', '', 'Calle 24 entre diagonal 23 y 29 kanasín centro', '', 'Lunes a viernes 8 a 10', '', 'active', CURRENT_TIMESTAMP, 'formulario-homologado-2026');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_groups (zone, name, city, leader_name, whatsapp, email, facebook, address, maps_url, schedules, session_types, status, verified_at, updated_by) VALUES ('Jaguar', 'Cazadores de Sueños', 'Yucatán', 'Angelica Pacheco', '9999075416', 'iris.angy0405@gmail.com', '', 'Calle 39a num 832b x 106 y 108 hacienda caucel cod p. 93714', '', 'De lunes a sabado de 8 a 10', '', 'active', CURRENT_TIMESTAMP, 'formulario-homologado-2026');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_groups (zone, name, city, leader_name, whatsapp, email, facebook, address, maps_url, schedules, session_types, status, verified_at, updated_by) VALUES ('Jaguar', 'Dosis de Amor', 'Yucatán', 'Omar Jesus Canul Castillo', '9992426629', 'omarcanul04@gmail.com', '', 'C75 1110 x 136 y 30 fracc tulipanes cinturón verde cp97249 Mérida', '', 'Lunes a sábado 8:00pm a 10:00pm', '', 'active', CURRENT_TIMESTAMP, 'formulario-homologado-2026');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_groups (zone, name, city, leader_name, whatsapp, email, facebook, address, maps_url, schedules, session_types, status, verified_at, updated_by) VALUES ('Jaguar', 'Una Segunda Oportunidad', 'Yucatán', 'Jair Alejandro Cetz Be', '9996458360', 'cetzjair1@gmail.com', '', 'C 15x24y26 cacalchen yuc 97460', '', 'Lunes a viernes 8:30 a10:30', '', 'active', CURRENT_TIMESTAMP, 'formulario-homologado-2026');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_groups (zone, name, city, leader_name, whatsapp, email, facebook, address, maps_url, schedules, session_types, status, verified_at, updated_by) VALUES ('Jaguar', 'Sendero de Vida', 'Yucatán', 'Limbert Gerardo Mukul Uc', '9991611300', 'lmukuluc@icloud.com', '', 'Calle 23 #228 x 4 y 6 col. Santa María chuburna Merida Yucatán', '', 'Lunes a viernes 8:30pm a 10:30pm', '', 'active', CURRENT_TIMESTAMP, 'formulario-homologado-2026');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_groups (zone, name, city, leader_name, whatsapp, email, facebook, address, maps_url, schedules, session_types, status, verified_at, updated_by) VALUES ('Jaguar', 'Río Lagartos', 'Yucatán', 'Maria Graviana Ku May', '9861064396', 'mariagravianak@gmail.com', '', 'Calle 10#172', '', 'De lunes a viernes de 8 a10 de la noche', '', 'active', CURRENT_TIMESTAMP, 'formulario-homologado-2026');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_groups (zone, name, city, leader_name, whatsapp, email, facebook, address, maps_url, schedules, session_types, status, verified_at, updated_by) VALUES ('Jaguar', 'La Vida Continúa', 'Chicxulub Pueblo, Yucatán', 'Mari IX', '9993529190', 'ixmaria644@gmail.com', '', 'Calle 10x23y25 colonia el huas chicxulub pueblo 97340', '', 'Lunes a viernes 8;30 p. m. a 10 :30pm', '', 'active', CURRENT_TIMESTAMP, 'formulario-homologado-2026');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_groups (zone, name, city, leader_name, whatsapp, email, facebook, address, maps_url, schedules, session_types, status, verified_at, updated_by) VALUES ('Jaguar', 'La Quinta Tradición', 'Yucatán', 'Franck Lugo', '9991917406', 'nojoch1021@gmail.com', '', 'C. 26 G #46 x c. 28 y c.9 col. Lienzo charro 97390 Umán yucatán', '', 'Lunes a sábado 8:30 p. m. a 10:30 p. m..', '', 'active', CURRENT_TIMESTAMP, 'formulario-homologado-2026');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_groups (zone, name, city, leader_name, whatsapp, email, facebook, address, maps_url, schedules, session_types, status, verified_at, updated_by) VALUES ('Jaguar', 'De la Calle a la Vida', 'Yucatán', 'Gonzalo Barba', '9991295885', 'gsangerman@gmail.com', '', 'Calle 88 número 497 por 59a y 49 centro', '', 'Lunes a domingo de 8:00 a 10:00 p. m.', '', 'active', CURRENT_TIMESTAMP, 'formulario-homologado-2026');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_groups (zone, name, city, leader_name, whatsapp, email, facebook, address, maps_url, schedules, session_types, status, verified_at, updated_by) VALUES ('Jaguar', 'De las Tinieblas a la Luz', 'Yucatán', 'Eligio Chan Yam', '9992980782', 'eligiochanyam7@gmail.com', '', 'Calle 18 x23 y 25 colonia centro Sotuta yucatan', '', 'Lunes a sabado de 8:00 p. m. a 10:00 p. m.', '', 'active', CURRENT_TIMESTAMP, 'formulario-homologado-2026');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_groups (zone, name, city, leader_name, whatsapp, email, facebook, address, maps_url, schedules, session_types, status, verified_at, updated_by) VALUES ('Tiburón', 'Valor para Cambiar', 'Chetumal, Quintana Roo', 'Reyna Yanet Rojas Hernández', '9831262979', 'rojas.fisio27@gmail.com', '', 'Luis Moya entre Benjamín Hill y Ramón Corona #496', '', 'Lunes a Sábado 8:00pm a 10:00pm', 'Sesión Principal (dos Horas por la Noche)', 'active', CURRENT_TIMESTAMP, 'formulario-homologado-2026');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_groups (zone, name, city, leader_name, whatsapp, email, facebook, address, maps_url, schedules, session_types, status, verified_at, updated_by) VALUES ('Tiburón', 'Doceava Promesa', 'Valladolid, Yucatán', 'Jesus Miguel Kuyoc Arjona', '9984902495', 'pinkyarjonajesus423@gmail.com', '', 'Calle 30 N.136 x 19 y 21 colonia Fernando novelo código postal 97780', '', 'Lunes-sabado 8pm a 10 p. m.', 'Sesión Principal (dos Horas por la Noche)', 'active', CURRENT_TIMESTAMP, 'formulario-homologado-2026');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_groups (zone, name, city, leader_name, whatsapp, email, facebook, address, maps_url, schedules, session_types, status, verified_at, updated_by) VALUES ('Tiburón', 'Nuevo Corazón', 'Cancún, Quintana Roo', 'Irene Jiménez Pat', '9984073927', 'irenejimenez300470@gmail.com', '', 'Calle 56 poniente Sm 94', 'https://maps.app.goo.gl/X4TzV8suEqc25TyW8?g_st=ic', 'Lunes a a sábado de 8 a 10 p. m.', 'Sesión Principal (dos Horas por la Noche)', 'active', CURRENT_TIMESTAMP, 'formulario-homologado-2026');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_groups (zone, name, city, leader_name, whatsapp, email, facebook, address, maps_url, schedules, session_types, status, verified_at, updated_by) VALUES ('Águila', 'Aprendiendo a Vivir', 'Lerdo, Durango', 'Elisa Mani Agüero', '8715167508', 'elisa.maniag10@gmail.com', '', 'Av Castilagua 905 acertada los Reyes Lerdo Durango', '', 'De lunes a domingo de 8 a 10', 'Sesión Principal (dos Horas por la Noche)', 'active', CURRENT_TIMESTAMP, 'formulario-homologado-2026');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_groups (zone, name, city, leader_name, whatsapp, email, facebook, address, maps_url, schedules, session_types, status, verified_at, updated_by) VALUES ('Águila', 'Almas Renovadas', '', 'Carolina Ibañez Aguilera', '8713162580', 'carolinaaguilera0571@gmail.com', '', '', '', 'Todos los días 8a 10', 'Sesión Principal (dos Horas por la Noche), Jóvenes (15 - 25 Años Aprox)', 'active', CURRENT_TIMESTAMP, 'formulario-homologado-2026');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_groups (zone, name, city, leader_name, whatsapp, email, facebook, address, maps_url, schedules, session_types, status, verified_at, updated_by) VALUES ('Colibrí', 'Torre de Amor y Esperanza', 'Tenango del Valle, Estado de México', 'Maria Angélica Perez Rico', '7223654705', 'angiperez1009@gmail.com', '', 'Mariano Matamoros #117 col Guadalupe c.p.52300 Tenango del valle', 'https://maps.app.goo.gl/3HGRPG1Cq1eKFAje9', 'De lunes a viernes', 'Sesión Principal (dos Horas por la Noche)', 'active', CURRENT_TIMESTAMP, 'formulario-homologado-2026');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_groups (zone, name, city, leader_name, whatsapp, email, facebook, address, maps_url, schedules, session_types, status, verified_at, updated_by) VALUES ('Colibrí', 'El Jaguar', 'Ciudad de México, Estado de México', 'Stephanie Abigail Saravia Nava', '7823273472', 'pichardosaraviamauroanuar@gmail.com', '', 'Av niños Heroes 64 COL san luis atlilco', '', 'Lunes a domingo 8pm a 10pm', 'Sesión Principal (dos Horas por la Noche)', 'active', CURRENT_TIMESTAMP, 'formulario-homologado-2026');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_groups (zone, name, city, leader_name, whatsapp, email, facebook, address, maps_url, schedules, session_types, status, verified_at, updated_by) VALUES ('Colibrí', 'Como la Brisa', 'Toluca Centro', 'Georgina Verónica', '7223616478', 'gina.auge@hotmail.com', '', 'Aún sin un Domi', '', 'Lunes a viernes 7:30 a 9:30 p. m.', 'Sesión Principal (dos Horas por la Noche)', 'active', CURRENT_TIMESTAMP, 'formulario-homologado-2026');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_groups (zone, name, city, leader_name, whatsapp, email, facebook, address, maps_url, schedules, session_types, status, verified_at, updated_by) VALUES ('Águila', 'Gracias por Existir', 'Torreón, Coahuila', 'Luis Guillermo Romero Maldonado', '8714036868', 'gmoromerio02@hotmail.com', '', 'Calle de los Actores #135 Colonia Rincón la Merced', '', 'Lunes a Domingo 8 a 10 y domingos 5 a 7', 'Sesión Principal (dos Horas por la Noche), Media Noche (nocturna), Jóvenes (15 - 25 Años Aprox), ADN (jóvenes Adictos)', 'active', CURRENT_TIMESTAMP, 'formulario-homologado-2026');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_groups (zone, name, city, leader_name, whatsapp, email, facebook, address, maps_url, schedules, session_types, status, verified_at, updated_by) VALUES ('Águila', 'Persistir en el Sendero', 'Matamoros, Coahuila', 'Eibbie Michelle Mejia de la Cruz', '8717557652', 'eibbiemejia51@gmail.com', '', 'Calle Guillermo Prieto #212 Col centro', '', 'Lunes a sabado 8 a 10 p. m.', 'Sesión Principal (dos Horas por la Noche)', 'active', CURRENT_TIMESTAMP, 'formulario-homologado-2026');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_groups (zone, name, city, leader_name, whatsapp, email, facebook, address, maps_url, schedules, session_types, status, verified_at, updated_by) VALUES ('Tiburón', 'Alfa y Omega', 'Playa del Carmen, Quintana Roo', 'Elena Dominguez', '9841465503', 'elen_dguez@hotmail.com', 'https://www.facebook.com/share/1AvjEdKFXy/', 'Av. Constituyentes frente al willis pescadores 2, solidaridad.', '', 'Lunes a sábado 8:30 a 10:30', 'Sesión Principal (dos Horas por la Noche)', 'active', CURRENT_TIMESTAMP, 'formulario-homologado-2026');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_groups (zone, name, city, leader_name, whatsapp, email, facebook, address, maps_url, schedules, session_types, status, verified_at, updated_by) VALUES ('Colibrí', 'Amanece', 'Malinalco, México', 'Roberto Cabañas', '7225502739', '', '', 'Camino a Chalma 22 barrio Santa María Malinalco', '', 'Lunes miércoles jueves viernes 7pm', 'Sesión Principal (dos Horas por la Noche)', 'active', CURRENT_TIMESTAMP, 'formulario-homologado-2026');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_groups (zone, name, city, leader_name, whatsapp, email, facebook, address, maps_url, schedules, session_types, status, verified_at, updated_by) VALUES ('Colibrí', 'Hazme Brillar', 'Miacatlán, Estado de Morelos', 'Javier Juarez Martinez', '5525086084', '', '', 'Calle Aldama y avenida matamoros, 62601, Miacatlan', '', 'Lunes a viernes 7 a 9 p. m.', 'Sesión Principal (dos Horas por la Noche)', 'active', CURRENT_TIMESTAMP, 'formulario-homologado-2026');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_groups (zone, name, city, leader_name, whatsapp, email, facebook, address, maps_url, schedules, session_types, status, verified_at, updated_by) VALUES ('Colibrí', 'Soy un Milagro', 'Poza Rica, Veracruz', 'Christian Jesus Ramírez Aguilar', '7821708555', 'cjra120785@gmail.com', '', 'María Esperanza Morales 52 colonia magisterios', '', 'Lunes a viernes 7:00 a 9:00pm', 'Sesión Principal (dos Horas por la Noche)', 'active', CURRENT_TIMESTAMP, 'formulario-homologado-2026');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_groups (zone, name, city, leader_name, whatsapp, email, facebook, address, maps_url, schedules, session_types, status, verified_at, updated_by) VALUES ('Águila', 'Corazones Guerreros', 'Gómez Palacio, Durango', 'Laura Graciela García Chacon', '8715829651', 'endyferacos3@gmail.com', '', 'Avenida bravo 305 Colonia refugio', '', 'De lunes a domingo 8 a 10', 'Sesión Principal (dos Horas por la Noche), Media Noche (nocturna)', 'active', CURRENT_TIMESTAMP, 'formulario-homologado-2026');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_groups (zone, name, city, leader_name, whatsapp, email, facebook, address, maps_url, schedules, session_types, status, verified_at, updated_by) VALUES ('Colibrí', 'Un Acto de Fe', 'Toluca, Estado de México', 'Kenia Consuelo Novia García', '7293781119', 'abrilkenia23@gmail.com', '', 'Calle lago saldo 119 El seminario primera sección 50170 Toluca de lerdo', 'https://maps.app.goo.gl/h5NiYa3auNQ7pDdNA?g_st=aw', '7;00 a 9:00 p. m.', 'Sesión Principal (dos Horas por la Noche)', 'active', CURRENT_TIMESTAMP, 'formulario-homologado-2026');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_groups (zone, name, city, leader_name, whatsapp, email, facebook, address, maps_url, schedules, session_types, status, verified_at, updated_by) VALUES ('Águila', 'Vidas Milagrosas', 'Torreón, Coahuila', 'José Antonio Morales Márquez', '8714730101', 'joanmarkesti@gmail.com', '', 'Av. De los santos #146 col. Rincón San Salvador c.p.27000 torreón Coah.', '', 'Lunes a domingo 8pm 10 p. m.', 'Sesión Principal (dos Horas por la Noche)', 'active', CURRENT_TIMESTAMP, 'formulario-homologado-2026');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_groups (zone, name, city, leader_name, whatsapp, email, facebook, address, maps_url, schedules, session_types, status, verified_at, updated_by) VALUES ('Tiburón', 'Álvaro Obregón', 'Chetumal, Municipio Othón P. Blanco, Quintana Roo', 'Rubén Garduza Salaya', '9832117662', 'rubengarduza@hotmail.com', '', 'C.Mario Villanueva madrit, y c. Periférico c. P 77710', '', 'De lunes a sábado de 7 de la noche a 9 de la noche', 'Alateen (primaria 6 - 10 Años)', 'active', CURRENT_TIMESTAMP, 'formulario-homologado-2026');
--> statement-breakpoint
INSERT OR IGNORE INTO directory_groups (zone, name, city, leader_name, whatsapp, email, facebook, address, maps_url, schedules, session_types, status, verified_at, updated_by) VALUES ('Tiburón', 'La Armadura', 'Playa del Carmen, Quintana Roo', 'Jose Alberto Aldana Vivas', '9843174060', 'gdll.armadura@gmail.com', '', 'Palma ribbon #30 fracc. Palmas 2 c.p.77714', '', 'Sábado a domingo 8 a 10 p. m.', 'Sesión Principal (dos Horas por la Noche)', 'active', CURRENT_TIMESTAMP, 'formulario-homologado-2026');
--> statement-breakpoint
INSERT OR REPLACE INTO content_settings (key, value, updated_at) VALUES ('directory_catalog_homogeneous_2026_08_26', 'applied', CURRENT_TIMESTAMP);
