"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";
import { SubFooter, SubHeader } from "../section-shell";

const criteria = [
  ["Maltrato o abuso de autoridad", "Gritos, humillaciones, amenazas o uso del servicio para controlar."],
  ["Riesgos de seguridad", "Situaciones que comprometen la integridad física o emocional."],
  ["Confidencialidad", "Exposición indebida de procesos, testimonios o información sensible."],
  ["Conducta inapropiada", "Acciones que dañan la confianza del grupo o la comunidad."],
  ["Uso indebido de recursos", "Manejo poco claro de materiales, espacios o apoyos."],
  ["Orientación preventiva", "Dudas que conviene atender antes de que la situación crezca."],
];

const roleGuidance = [
  { role: "Padrinos y madrinas", rights: ["Servir con límites claros", "Pedir apoyo o relevo", "Recibir orientación institucional"], duties: ["No imponer ni humillar", "Respetar confidencialidad", "Reconocer los límites de su preparación"] },
  { role: "Líderes y OSG", rights: ["Recibir información vigente", "Solicitar acompañamiento", "Proponer mejoras con evidencia"], duties: ["Cuidar a las personas", "Rendir cuentas de su servicio", "Enviar cambios sensibles a aprobación"] },
  { role: "Militantes y miembros", rights: ["Ser tratados con dignidad", "Ser escuchados sin represalias", "Conocer reglas y canales de ayuda"], duties: ["Respetar acuerdos y espacios", "Cuidar la confidencialidad", "Participar con honestidad y responsabilidad"] },
];

export default function EthicsPage() {
  const [folio, setFolio] = useState("");
  function submit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault();
    setFolio(`FGDLL-2026-${Math.random().toString(36).slice(2, 6).toUpperCase()}`);
  }
  return <><div className="emergency">Si existe riesgo inmediato para tu vida o integridad física, llama al <a href="tel:911">911</a>.</div><SubHeader label="Ética y educación" /><main className="subpage ethics-page ethics-education-page">
    <section className="subhero ethics-hero"><div className="shell"><span className="eyebrow light">Ética · Derechos · Estructura</span><h1>Conocer nuestros límites<br /><em>también es cuidarnos.</em></h1><p>Un portal educativo para comprender derechos, responsabilidades, estructura institucional y canales de orientación dentro de FGDLL.</p><div className="hero-actions"><a className="button button-gold" href="#responsabilidades">Derechos y responsabilidades ↓</a><a className="button button-ghost" href="#organigrama">Ver organigrama</a></div></div></section>
    <section className="ethics-index"><div className="shell"><a href="#responsabilidades"><b>01</b><span>Derechos y responsabilidades</span></a><a href="#organigrama"><b>02</b><span>Organigrama institucional</span></a><a href="#asociacion"><b>03</b><span>FGDLL como Asociación Civil</span></a><a href="#reporte"><b>04</b><span>Orientación ética</span></a></div></section>
    <section className="section rights-section" id="responsabilidades"><div className="shell"><div className="section-heading split-heading"><div><span className="eyebrow">Educación para el servicio</span><h2>Derechos que protegen.<br />Responsabilidades que sostienen.</h2></div><p>El cargo nunca coloca a una persona por encima de la dignidad de otra. Cada función tiene facultades, límites y obligaciones concretas.</p></div><div className="role-rights-grid">{roleGuidance.map((item, index) => <article key={item.role}><header><span>0{index + 1}</span><h3>{item.role}</h3></header><div><section><h4>Derechos</h4><ul>{item.rights.map((right) => <li key={right}>{right}</li>)}</ul></section><section><h4>Responsabilidades</h4><ul>{item.duties.map((duty) => <li key={duty}>{duty}</li>)}</ul></section></div></article>)}</div><div className="rights-principle"><strong>Principio común</strong><p>Ningún servicio autoriza violencia, coerción, explotación, discriminación, exposición pública ni prácticas que sustituyan atención profesional.</p></div></div></section>
    <section className="section organization-section" id="organigrama"><div className="shell"><div className="section-heading split-heading"><div><span className="eyebrow light">Organigrama funcional</span><h2>Autoridad para servir.<br />Responsabilidad para responder.</h2></div><p>La estructura distribuye responsabilidades; no concede privilegios personales. El apadrinamiento acompaña transversalmente y no sustituye a los órganos institucionales.</p></div><div className="org-chart" aria-label="Organigrama funcional de FGDLL"><div className="org-node org-root"><small>PERSONA MORAL</small><strong>Fraternidad Guerreros de la Luz A.C.</strong></div><i /><div className="org-node org-council"><small>GOBIERNO Y CUSTODIA</small><strong>Consejo Directivo</strong></div><i /><div className="org-row"><div className="org-node"><small>COORDINACIÓN TERRITORIAL</small><strong>Delegados de zona</strong></div><div className="org-node org-side"><small>SERVICIO TRANSVERSAL</small><strong>Padrinos y madrinas</strong><span>Acompañan; no sustituyen autoridad institucional.</span></div></div><i /><div className="org-node"><small>RESPONSABILIDAD LOCAL</small><strong>Líderes de grupo</strong></div><i /><div className="org-row org-bottom"><div className="org-node"><strong>Sublíderes y OSG</strong></div><div className="org-node"><strong>Militantes y servidores</strong></div><div className="org-node"><strong>Miembros y comunidad</strong></div></div></div><p className="org-note">Este mapa explica la relación operativa general. Los estatutos, reglamentos y nombramientos vigentes determinan las facultades formales de cada órgano.</p></div></section>
    <section className="section association-section" id="asociacion"><div className="shell association-grid"><div><span className="eyebrow">Nosotros como A.C.</span><h2>Una organización con identidad, obligaciones y memoria institucional.</h2><p>Ser Asociación Civil significa que la fraternidad necesita acuerdos documentados, responsabilidades definidas, cuidado de recursos y continuidad más allá de las personas que temporalmente ocupan un servicio.</p><Link className="button button-outline" href="/portal">Consultar materiales de liderazgo →</Link></div><div className="association-pillars"><article><span>01</span><h3>Propósito común</h3><p>Orientar el servicio hacia la ayuda, la recuperación y el bienestar de la comunidad.</p></article><article><span>02</span><h3>Gobernanza</h3><p>Tomar decisiones mediante órganos, reglas, atribuciones y registros verificables.</p></article><article><span>03</span><h3>Rendición de cuentas</h3><p>Documentar acuerdos, uso de recursos, cambios de responsables y decisiones sensibles.</p></article><article><span>04</span><h3>Protección institucional</h3><p>Cuidar datos, nombre, patrimonio, materiales y confianza de quienes participan.</p></article></div></div></section>
    <section className="section reportable"><div className="shell"><div className="section-heading split-heading"><div><span className="eyebrow light">Criterios de orientación</span><h2>¿Qué situaciones requieren atención?</h2></div><p>El canal ético ordena hechos concretos y ayuda a canalizar; no debe utilizarse para rumores, represalias ni conflictos sin información verificable.</p></div><div className="criteria-grid">{criteria.map(([title, text], i) => <article key={title}><span>0{i + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="section report-section" id="reporte"><div className="shell report-layout"><div><span className="eyebrow">Orientación responsable</span><h2>Cuenta los hechos con orden y claridad.</h2><p>Esta demostración genera un folio únicamente en tu dispositivo. La información no se envía ni se guarda hasta conectar el canal institucional seguro.</p><ul><li>Describe qué pasó y dónde.</li><li>Indica la fecha aproximada.</li><li>Separa los hechos de interpretaciones.</li><li>Conserva evidencia sin difundirla.</li></ul></div><form onSubmit={submit} className="report-form"><label>Tipo de situación<select required defaultValue=""><option value="" disabled>Selecciona una opción</option>{criteria.map(([title]) => <option key={title}>{title}</option>)}</select></label><label>Zona o grupo relacionado<input placeholder="Ej. Zona Jaguar / Grupo…" /></label><label>Fecha aproximada<input type="date" /></label><label>Relato de los hechos<textarea required placeholder="Qué ocurrió, dónde, quiénes estaban presentes y qué necesitas que se revise…" /></label><button className="button button-gold" type="submit">Generar folio demostrativo</button>{folio && <div className="folio"><span>Folio local</span><strong>{folio}</strong><small>No confirma el envío de un reporte.</small></div>}</form></div></section>
    <section className="ethics-closing"><div className="shell"><h2>La luz también se cuida con límites.</h2><p>Proteger la dignidad, conocer la estructura y rendir cuentas fortalece el servicio.</p><Link className="button button-gold" href="/">Volver a información pública →</Link></div></section>
  </main><SubFooter /></>;
}
